defaults:
    - base_training_conf

train: True
consecutive_style_step: 2
batch_size: 8
repeat: 1000
learning_rate: 0.001
content_weight: 1
style_weight: 1000000
reg_weight: 0.00001
epochs: 50
log_interval: 50
adjust_learning_rate_interval: 5000
